<?php

namespace Tests\Unit;

use GuzzleHttp\Client;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestResponse;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Modules\Payment\Entities\Concerns\UsesUuid;
use Modules\Payment\Gateway\Sagepay\Payment;
use Modules\Payment\Gateway\Sagepay\VoidPayment;
use Psr\Http\Message\ResponseInterface;
use Tests\TestCase;

class DatabaseEntryPaymentTest extends TestCase
{
    protected $payload;
    protected $err_payload;
    protected $requestHeaders;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->payload = json_decode(
            '{
                    "transactionType": "Payment",
                    "transactionId": "A66F7DC8-705F-0512-C149-62AB40304FD8",
                    "cardDetails":{
                        "cardholderName": "Bruce Lee Fong Kong",
                        "cardNumber": "4929000000006",
                        "expiryDate": "0320",
                        "securityCode": "123"
                    },
                    "vendorTxCode": "EC1V-12654-",
                    "amount": 6325,
                    "currency": "GBP",
                    "description": "Demo transaction",
                    "apply3DSecure": "UseMSPSetting",
                    "customerFirstName": "Bruce",
                    "customerLastName": "Lee",
                    "customerEmail": "sam@johns.co.uk",
                    "billingAddress": {
                        "address1": "407 St. John Street",
                        "city": "London",
                        "postalCode": "EC1V 4AB",
                        "country": "GB"
                    },
                    "entryMethod": "Ecommerce",
                    "key": "dzlSN2ZSOWYxenhnYXNTNWVjNDZia05vaTFsekFDNGlrV1pxa2gxZnFFa1Z6RkxsS0M6enVBRnVpckM1UEc0bEoyMlQzcmxCdDRXY1NmcTRpOWdyblJOcWpHWktYVGhDOFMwVmkwakt3V21tMHc2RGhZd2Q=",
                    "vendorName": "rematchtest",
                    "baseUrl": "https://pi-test.sagepay.com/api/v1/",
                    "paymentType": "void"
                    }',
            true);

        $this->requestHeaders = [
            "Authorization" => "Basic dzlSN2ZSOWYxenhnYXNTNWVjNDZia05vaTFsekFDNGlrV1pxa2gxZnFFa1Z6RkxsS0M6enVBRnVpckM1UEc0bEoyMlQzcmxCdDRXY1NmcTRpOWdyblJOcWpHWktYVGhDOFMwVmkwakt3V21tMHc2RGhZd2Q=",
            "Content-Type" => "application/json",
            "vendorName" => "rematchtest"
        ];

    }

    /**
     * A basic test example.
     *
     * @test
     *
     * @return void
     * @throws \Exception
     */
    public function testShouldBeAbleToAddPaymentToDatabase()
    {

        $response = $this->withHeaders($this->requestHeaders)->postJson('/api/payment/pay', $this->payload);

        $result = $response->decodeResponseJson();

        unset($result['paymentMethod']); // remove sensitive info

        $this->assertArrayHasKey('statusDetail', $result);

        $this->assertEquals('The Authorisation was Successful.', $result['statusDetail']);

        $trans = new \Modules\Payment\Entities\Transaction();

        $trans->user_id = '04d7f995-ef33-4870-a214-4e21c51ff76e';
        $trans->transaction_id = $result['transactionId'];
        $trans->response_message = json_encode($result);

        $this->assertEquals($trans->getKeyType(), 'string');

    }

}
