<?php

namespace Tests\Unit;

use Dividebuy\Payment\Contracts\Card;
use GuzzleHttp\Client;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Modules\Payment\Gateway\Sagepay\Payment;
use Modules\Payment\Gateway\Sagepay\VoidPayment;
use Tests\TestCase;

class PaymentTest extends TestCase
{
    protected $payload;
    protected $requestHeaders;
    protected $err_payload;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->payload = json_decode(
            '{
                    "transactionType": "Payment",
                    "transactionId": "A66F7DC8-705F-0512-C149-62AB40304FD8",
                    "cardDetails":{
                        "cardholderName": "Bruce Lee Fong Kong",
                        "cardNumber": "4929000000006",
                        "expiryDate": "0320",
                        "securityCode": "123"
                    },
                    "vendorTxCode": "EC1V-12654-",
                    "amount": 156700,
                    "currency": "GBP",
                    "description": "Demo transaction",
                    "apply3DSecure": "UseMSPSetting",
                    "customerFirstName": "Bruce",
                    "customerLastName": "Lee",
                    "customerEmail": "sam@johns.co.uk",
                    "billingAddress": {
                        "address1": "407 St. John Street",
                        "city": "London",
                        "postalCode": "EC1V 4AB",
                        "country": "GB"
                    },
                    "entryMethod": "Ecommerce",
                    "key": "dzlSN2ZSOWYxenhnYXNTNWVjNDZia05vaTFsekFDNGlrV1pxa2gxZnFFa1Z6RkxsS0M6enVBRnVpckM1UEc0bEoyMlQzcmxCdDRXY1NmcTRpOWdyblJOcWpHWktYVGhDOFMwVmkwakt3V21tMHc2RGhZd2Q=",
                    "vendorName": "rematchtest",
                    "baseUrl": "https://pi-test.sagepay.com/api/v1/",
                    "paymentType": "void"
                    }',
            true);

        $this->requestHeaders = [
            "Authorization" => "Basic dzlSN2ZSOWYxenhnYXNTNWVjNDZia05vaTFsekFDNGlrV1pxa2gxZnFFa1Z6RkxsS0M6enVBRnVpckM1UEc0bEoyMlQzcmxCdDRXY1NmcTRpOWdyblJOcWpHWktYVGhDOFMwVmkwakt3V21tMHc2RGhZd2Q=",
            "Content-Type" => "application/json",
            "vendorName" => "rematchtest"
        ];

    }

    /**
     * A basic test example.
     *
     * @test
     *
     * @return void
     * @throws \Exception
     */
    public function testShouldBeAbleToMakePayment()
    {

        $response = $this->withHeaders([$this->requestHeaders, $this->payload])->post('/api/payment/pay', $this->payload, $this->requestHeaders);

        dump($response);
//
//        $result = $response->decodeResponseJson();
//
//        dump($result);

        $this->assertTrue(true);

//        $this->assertIsString($result['merchantSessionKey']);
//        $this->assertArrayHasKey('merchantSessionKey', $result);

    }

    /**
     * A basic test example.
     *
     * @test
     *
     * @return void
     * @throws \Exception
     */
    public function testShouldNotBeAbleToGenerateSessionToken()
    {

        $response = $this->withHeaders($this->requestHeaders)->post('/api/payment/session-token', $this->payload);

        $result = $response->decodeResponseJson();

        $this->assertIsString($result['merchantSessionKey']);
        $this->assertArrayHasKey('merchantSessionKey', $result);

    }
}
