<?php

namespace Tests\Unit;

use Dividebuy\Payment\Contracts\Card;
use GuzzleHttp\Client;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\JsonResponse;
use Modules\Payment\Gateway\Sagepay\Payment;
use Modules\Payment\Gateway\Sagepay\VoidPayment;
use Psr\Http\Message\ResponseInterface;
use Tests\TestCase;

class SessionTokenTest extends TestCase
{
    protected $payload;
    protected $err_payload;
    protected $requestHeaders;
    protected $requestMissingHeaders;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->payload = json_decode(
            '{
                    "cardDetails":{
                        "cardholderName": "Bruce Lee Fong Kong",
                        "cardNumber": "4929000000006",
                        "expiryDate": "0320",
                        "securityCode": "123"
                    },
                    "key": "dzlSN2ZSOWYxenhnYXNTNWVjNDZia05vaTFsekFDNGlrV1pxa2gxZnFFa1Z6RkxsS0M6enVBRnVpckM1UEc0bEoyMlQzcmxCdDRXY1NmcTRpOWdyblJOcWpHWktYVGhDOFMwVmkwakt3V21tMHc2RGhZd2Q=",
                    "vendorName": "rematchtest",
                    "baseUrl": "https://pi-test.sagepay.com/api/v1/"
                    }',
            true);

        $this->requestHeaders = [
            "Authorization" => "Basic dzlSN2ZSOWYxenhnYXNTNWVjNDZia05vaTFsekFDNGlrV1pxa2gxZnFFa1Z6RkxsS0M6enVBRnVpckM1UEc0bEoyMlQzcmxCdDRXY1NmcTRpOWdyblJOcWpHWktYVGhDOFMwVmkwakt3V21tMHc2RGhZd2Q=",
            "Content-Type" => "application/json",
            "vendorName" => "rematchtest"
        ];

    }

    /**
     * A basic test example.
     *
     * @test
     *
     * @return void
     * @throws \Exception
     */
    public function testShouldBeAbleToGenerateSessionToken()
    {

        $response = $this->post('/api/payment/session-token', $this->payload, $this->requestHeaders);

        $result = $response->decodeResponseJson();

        $this->assertIsString($result['merchantSessionKey']);
        $this->assertArrayHasKey('merchantSessionKey', $result);

    }

    /**
     * A basic test example.
     *
     * @test
     *
     * @return void
     * @throws \Exception
     */
    public function testShouldNotBeAbleToGenerateSessionToken()
    {

        $response = $this->withHeaders($this->requestHeaders)->post('/api/payment/session-token', $this->payload);

        $result = $response->decodeResponseJson();

        $this->assertIsString($result['merchantSessionKey']);
        $this->assertArrayHasKey('merchantSessionKey', $result);

    }

}
